//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELEMENT_ZAMOWIENIA
    {
        public int ID_ELEMENT { get; set; }
        public int ILOSC { get; set; }
        public int FK_ID_ZAMOWIENIA { get; set; }
        public int FK_ID_POZYCJI { get; set; }
    

    }
}
