//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS
    {

    
        public int ID_STATUS { get; set; }
        public string NAZWA { get; set; }
    
     
    }
}
