CREATE TABLE "PRACOWNIK" (
  "ID_PRACOWNIKA" int identity (1,1)NOT NULL,
  "IMIE" VARCHAR(20) NOT NULL,
  "NAZWISKO" VARCHAR(20) NOT NULL,
  CONSTRAINT "CONSTRAINT2" 
    PRIMARY KEY ( "ID_PRACOWNIKA") 
    );
	CREATE TABLE "MENU" (
  "ID_MENU" int identity(1,1) NOT NULL,
  "NAZWA" VARCHAR(20) NOT NULL,
  CONSTRAINT "CONSTRAINT3" 
    PRIMARY KEY ( "ID_MENU") 
     );

	 CREATE TABLE "KATEGORIA" (
  "ID_KATEGORIA" int identity (1,1)NOT NULL,
  "NAZWA" VARCHAR(20) NOT NULL,
  CONSTRAINT "CONSTRAINT4" 
    PRIMARY KEY ( "ID_KATEGORIA") 
    );
	CREATE TABLE "POZYCJA_MENU" (
  "ID_POZYCJI" int identity(1,1) NOT NULL,
  "CENA_BRUTTO" FLOAT NOT NULL,
  "NAZWA" VARCHAR(20) NOT NULL,
  "FK_IDKATEGORIA" int NOT NULL,
  "FK_IDMENU" int NOT NULL,
  CONSTRAINT "CONSTRAINT5" 
    PRIMARY KEY ( "ID_POZYCJI") 
    ,
  CONSTRAINT "CONSTRAINT6" 
    FOREIGN KEY ( "FK_IDKATEGORIA")
       REFERENCES "KATEGORIA" ( ID_KATEGORIA) 
    ,
  CONSTRAINT "CONSTRAINT7" 
    FOREIGN KEY ( "FK_IDMENU")
       REFERENCES "MENU" ( ID_MENU) 
    );

		CREATE TABLE "STATUS" (
  "ID_STATUS" int identity(1,1) NOT NULL,
  "NAZWA" VARCHAR(20) NOT NULL,
  CONSTRAINT "CONSTRAINT1" 
    PRIMARY KEY ( "ID_STATUS") 
     );

	CREATE TABLE "ZAMOWIENIE" (
  "ID_ZAMOWIENIA" int identity (1,1) NOT NULL,
  "CENA" FLOAT NOT NULL,
  "DATA_PRZGOTOWANIA" DATE NULL,
  "DATA_WYDANIA" DATE NULL,
  "DATA_ZLOZENIA" DATE NOT NULL,
  "UWAGI" VARCHAR(100) NULL,
  "CZY_ZAPLACONE" int NOT NULL,
  "FK_STATUS" int NOT NULL,
  "FK_PRACOWNIK_WYDAJACY" int NULL,
  "FK_PRACOWNIK_PRZYJMUJACY" int NOT NULL,
  CONSTRAINT "CONSTRAINT8" 
    PRIMARY KEY ( "ID_ZAMOWIENIA") 
     
    ,
  CONSTRAINT "CONSTRAINT9" 
    FOREIGN KEY ( "FK_STATUS")
       REFERENCES "STATUS" ( ID_STATUS) 
     
    ,
  CONSTRAINT "CONSTRAINT10" 
    FOREIGN KEY ( "FK_PRACOWNIK_PRZYJMUJACY")
       REFERENCES "PRACOWNIK" ( ID_PRACOWNIKA) 
    ,
  CONSTRAINT "CONSTRAINT11" 
    FOREIGN KEY ( "FK_PRACOWNIK_WYDAJACY")
       REFERENCES "PRACOWNIK" ( ID_PRACOWNIKA) 
    
    ,
  CONSTRAINT "CHECK1" 
    CHECK (CZY_ZAPLACONE BETWEEN 0 and 1) 
    );

	CREATE TABLE "REALIZACJA_ZAMOWIENIA" (
  "ID_REALIZACJI" int identity (1,1) NOT NULL,
  "FK_ID_PRACOWNIKA" int NOT NULL,
  "FK_ID_ZAMOWIENIA" int NOT NULL,
  CONSTRAINT "CONSTRAINT12" 
    PRIMARY KEY ( "ID_REALIZACJI") 
     
    ,
  CONSTRAINT "CONSTRAINT13" 
    FOREIGN KEY ( "FK_ID_PRACOWNIKA")
       REFERENCES "PRACOWNIK" ( ID_PRACOWNIKA) 
     
    ,
  CONSTRAINT "CONSTRAINT14" 
    FOREIGN KEY ( "FK_ID_ZAMOWIENIA")
       REFERENCES "ZAMOWIENIE" ( ID_ZAMOWIENIA) 
     
    );

	CREATE TABLE "ELEMENT_ZAMOWIENIA" (
  "ID_ELEMENT" int identity(1,1) NOT NULL,
  "ILOSC" int NOT NULL,
  "FK_ID_ZAMOWIENIA" int NOT NULL,
  "FK_ID_POZYCJI" int NOT NULL,
  CONSTRAINT "CONSTRAINT15" 
    PRIMARY KEY ( "ID_ELEMENT") 
     
    ,
  CONSTRAINT "CONSTRAINT16" 
    FOREIGN KEY ( "FK_ID_ZAMOWIENIA")
       REFERENCES "ZAMOWIENIE" ( ID_ZAMOWIENIA) 
     
    ,
  CONSTRAINT "CONSTRAINT17" 
    FOREIGN KEY ( "FK_ID_POZYCJI")
       REFERENCES "POZYCJA_MENU" ( ID_POZYCJI) 
     
    );