//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serwer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class POZYCJA_MENU
    {
        public int ID_POZYCJI { get; set; }
        public double CENA_BRUTTO { get; set; }
        public string NAZWA { get; set; }
        public int FK_IDKATEGORIA { get; set; }
        public int FK_IDMENU { get; set; }
    }
}
