//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serwer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRACOWNIK
    {
        public int ID_PRACOWNIKA { get; set; }
        public string IMIE { get; set; }
        public string NAZWISKO { get; set; }
    }
}
