//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serwer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class REALIZACJA_ZAMOWIENIA
    {
        public int ID_REALIZACJI { get; set; }
        public int FK_ID_PRACOWNIKA { get; set; }
        public int FK_ID_ZAMOWIENIA { get; set; }
    }
}
