//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serwer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAMOWIENIE
    {
        public int ID_ZAMOWIENIA { get; set; }
        public double CENA { get; set; }
        public Nullable<System.DateTime> DATA_PRZGOTOWANIA { get; set; }
        public Nullable<System.DateTime> DATA_WYDANIA { get; set; }
        public System.DateTime DATA_ZLOZENIA { get; set; }
        public string UWAGI { get; set; }
        public int CZY_ZAPLACONE { get; set; }
        public int FK_STATUS { get; set; }
        public Nullable<int> FK_PRACOWNIK_WYDAJACY { get; set; }
        public int FK_PRACOWNIK_PRZYJMUJACY { get; set; }
    }
}
